apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-project
spec:
  selector:
    matchLabels:
      app: eks-project
  replicas: 2

  template:
    metadata:
      labels:
        app: eks-project
    spec:
      containers:
      - name: eks-project
        image: jch941022/eks-project-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: persistent-storage1
          mountPath: /dpod1
      volumes:
        - name: persistent-storage1
         persistentVolumeClaim:
           claimName: efs-pv-claim
